### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by uraway** [uraway/markdown-toc-plus#1]
TODOITEMS
:bowtie:
- [x] LICENSE
- [x] README usage gif
- [ ] solve the problem that this package treats comments(#) as headers
- [x] fix line bug after TOC
